# Generated by Django 6.0.5 on 2026-05-29 20:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('school', 'School'), ('college', 'College / Sixth Form'), ('university', 'University'), ('work', 'Work'), ('online', 'Online'), ('family', 'Family'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('colour_hex', models.CharField(default='#F3A0A8', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('nickname', models.CharField(blank=True, max_length=80)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='friend_profiles/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('how_we_met', models.TextField(blank=True)),
                ('tier', models.CharField(choices=[('inner_circle', 'Inner Circle'), ('friend', 'Friend'), ('archive', 'Archive')], default='friend', max_length=30)),
                ('favourite_colour', models.CharField(blank=True, max_length=80)),
                ('favourite_food', models.CharField(blank=True, max_length=120)),
                ('favourite_restaurant', models.CharField(blank=True, max_length=120)),
                ('favourite_alcoholic_drink', models.CharField(blank=True, max_length=120)),
                ('favourite_season', models.CharField(blank=True, max_length=80)),
                ('morning_or_night', models.CharField(blank=True, choices=[('', 'Unknown / Not added'), ('morning', 'Morning person'), ('night', 'Night person'), ('both', 'Both'), ('neither', 'Neither')], max_length=20)),
                ('mbti', models.CharField(blank=True, choices=[('', 'Unknown / Not added'), ('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP')], max_length=10)),
                ('zodiac', models.CharField(blank=True, choices=[('', 'Unknown / Not added'), ('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=20)),
                ('hobbies', models.TextField(blank=True)),
                ('sports_team', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.CharField(choices=[('manual', 'Manual entry'), ('google_form', 'Google Form'), ('spreadsheet', 'Spreadsheet'), ('other', 'Other')], default='manual', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friends', to='friends.connectiongroup')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='ExtendedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_song', models.CharField(blank=True, max_length=150)),
                ('favourite_movie', models.CharField(blank=True, max_length=150)),
                ('favourite_show', models.CharField(blank=True, max_length=150)),
                ('dream_trip', models.CharField(blank=True, max_length=150)),
                ('gift_ideas', models.TextField(blank=True)),
                ('inside_jokes', models.TextField(blank=True)),
                ('friendship_story', models.TextField(blank=True)),
                ('favourite_memory', models.TextField(blank=True)),
                ('private_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_profile', to='friends.friend')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=160)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('mood', models.CharField(blank=True, max_length=80)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, for example: cinema, school, funny', max_length=255)),
                ('is_favourite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='memories', to='friends.friend')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('taken_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='friends.friend')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='friends.memory')),
            ],
            options={
                'ordering': ['-taken_on', '-created_at'],
            },
        ),
    ]
