# Generated by Django 6.0.5 on 2026-05-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedprofile',
            name='biggest_fear',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='comfort_food',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='dream_destination',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='favourite_barbie_film',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='favourite_designer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='favourite_disney_film',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='first_impression_of_me',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='hogwarts_house',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='love_language_for_you',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='love_language_to_other',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='scent_family',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='shoe_brand',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='shoe_type',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='extendedprofile',
            name='zodiac_moon',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
